# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime

class AllocationMapBasisValue(BaseModel):
    """
    The value one investor record is weighted by when an Allocation Map is resolved.  # noqa: E501
    """
    investor_record_id:  StrictStr = Field(...,alias="investorRecordId", description="The investor record the basis value belongs to.") 
    basis_value: Union[StrictFloat, StrictInt] = Field(description="The value the investor record is weighted by, for example its commitment.", alias="basisValue")
    currency:  Optional[StrictStr] = Field(None,alias="currency", description="The currency the basis value is held in. Absent means the base currency of the map's member fund. When the basis values span more than one currency, each is translated into the fund's base currency at the spot rate on the event date, from the fund's ABOR recipe, before it weights the allocation. The rate on the event date is the latest quote at or before 00:00 UTC on that date.") 
    __properties = ["investorRecordId", "basisValue", "currency"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AllocationMapBasisValue:
        """Create an instance of AllocationMapBasisValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if currency (nullable) is None
        # and __fields_set__ contains the field
        if self.currency is None and "currency" in self.__fields_set__:
            _dict['currency'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AllocationMapBasisValue:
        """Create an instance of AllocationMapBasisValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AllocationMapBasisValue.parse_obj(obj)

        _obj = AllocationMapBasisValue.parse_obj({
            "investor_record_id": obj.get("investorRecordId"),
            "basis_value": obj.get("basisValue"),
            "currency": obj.get("currency")
        })
        return _obj

AllocationMapBasisValue.update_forward_refs()
