# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid.models.fund_structure_edge import FundStructureEdge
from lusid.models.fund_structure_node import FundStructureNode

class FundStructureMemberRequest(BaseModel):
    """
    A member to add to a Fund Structure: the node, and the links that join it to members already in the structure.  # noqa: E501
    """
    node: FundStructureNode
    edges: Optional[List[FundStructureEdge]] = Field(default=None, description="The links joining the new node to members already in the structure. May be empty for a member that is linked later.")
    __properties = ["node", "edges"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FundStructureMemberRequest:
        """Create an instance of FundStructureMemberRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of node
        if self.node:
            _dict['node'] = self.node.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in edges (list)
        _items = []
        if self.edges:
            for _item in self.edges:
                if _item:
                    _items.append(_item.to_dict())
            _dict['edges'] = _items
        # set to None if edges (nullable) is None
        # and __fields_set__ contains the field
        if self.edges is None and "edges" in self.__fields_set__:
            _dict['edges'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FundStructureMemberRequest:
        """Create an instance of FundStructureMemberRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FundStructureMemberRequest.parse_obj(obj)

        _obj = FundStructureMemberRequest.parse_obj({
            "node": FundStructureNode.from_dict(obj.get("node")) if obj.get("node") is not None else None,
            "edges": [FundStructureEdge.from_dict(_item) for _item in obj.get("edges")] if obj.get("edges") is not None else None
        })
        return _obj

FundStructureMemberRequest.update_forward_refs()
