# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid.models.payment_details_applicable_entity import PaymentDetailsApplicableEntity
from lusid.models.payment_details_series_identifiers import PaymentDetailsSeriesIdentifiers
from lusid.models.resource_id import ResourceId

class PaymentDetailsReferenceResponse(BaseModel):
    """
    Response representation of a Payment Details reference. Extends the request shape with  a system-populated relational dataset definition identifier.  # noqa: E501
    """
    relational_dataset_definition_id: Optional[ResourceId] = Field(default=None, alias="relationalDatasetDefinitionId")
    series_scope:  StrictStr = Field(...,alias="seriesScope", description="The scope of the relational datapoint. May differ from the scope of the dataset definition.") 
    applicable_entity: PaymentDetailsApplicableEntity = Field(alias="applicableEntity")
    series_identifiers: PaymentDetailsSeriesIdentifiers = Field(alias="seriesIdentifiers")
    effective_date: datetime = Field(description="The effective date of the relational datapoint observation to retrieve. ISO 8601 datetime.", alias="effectiveDate")
    as_at_date: datetime = Field(description="The as-at date of the relational datapoint observation to retrieve. ISO 8601 datetime.", alias="asAtDate")
    __properties = ["relationalDatasetDefinitionId", "seriesScope", "applicableEntity", "seriesIdentifiers", "effectiveDate", "asAtDate"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PaymentDetailsReferenceResponse:
        """Create an instance of PaymentDetailsReferenceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of relational_dataset_definition_id
        if self.relational_dataset_definition_id:
            _dict['relationalDatasetDefinitionId'] = self.relational_dataset_definition_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of applicable_entity
        if self.applicable_entity:
            _dict['applicableEntity'] = self.applicable_entity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of series_identifiers
        if self.series_identifiers:
            _dict['seriesIdentifiers'] = self.series_identifiers.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PaymentDetailsReferenceResponse:
        """Create an instance of PaymentDetailsReferenceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PaymentDetailsReferenceResponse.parse_obj(obj)

        _obj = PaymentDetailsReferenceResponse.parse_obj({
            "relational_dataset_definition_id": ResourceId.from_dict(obj.get("relationalDatasetDefinitionId")) if obj.get("relationalDatasetDefinitionId") is not None else None,
            "series_scope": obj.get("seriesScope"),
            "applicable_entity": PaymentDetailsApplicableEntity.from_dict(obj.get("applicableEntity")) if obj.get("applicableEntity") is not None else None,
            "series_identifiers": PaymentDetailsSeriesIdentifiers.from_dict(obj.get("seriesIdentifiers")) if obj.get("seriesIdentifiers") is not None else None,
            "effective_date": obj.get("effectiveDate"),
            "as_at_date": obj.get("asAtDate")
        })
        return _obj

PaymentDetailsReferenceResponse.update_forward_refs()
