# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid.models.resource_id import ResourceId

class QualifierDefinition(BaseModel):
    """
    A qualifier as returned on read: the request shape plus the value type resolved from its data type.  # noqa: E501
    """
    key:  Optional[StrictStr] = Field(None,alias="key", description="The key by which the qualifier is addressed, for example 'direction'. Addressed in filters, sort orders and derivation formulae as Properties[{propertyKey}].Qualifiers[{qualifierKey}]. Validated under the same rules as a property code.") 
    display_name:  Optional[StrictStr] = Field(None,alias="displayName", description="The display name of the qualifier.") 
    description:  Optional[StrictStr] = Field(None,alias="description", description="Describes the qualifier. Optional; null where not supplied.") 
    data_type_id: Optional[ResourceId] = Field(default=None, alias="dataTypeId")
    value_type:  Optional[StrictStr] = Field(None,alias="valueType", description="The type of value this qualifier carries, resolved from its data type. Available values: String, Int, Decimal, DateTime, Boolean, Map, List, PropertyArray, Percentage, Code, Id, Uri, CurrencyAndAmount, TradePrice, Currency, MetricValue, ResourceId, ResultValue, CutLocalTime, DateOrCutLabel, UnindexedText.") 
    is_required: Optional[StrictBool] = Field(default=None, description="Whether a value for this qualifier must be supplied when a value of the property is written. Defaults to false, and is returned as a boolean rather than as null. Validated on write only, so setting it true does not retroactively invalidate values stored before the change.", alias="isRequired")
    __properties = ["key", "displayName", "description", "dataTypeId", "valueType", "isRequired"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QualifierDefinition:
        """Create an instance of QualifierDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of data_type_id
        if self.data_type_id:
            _dict['dataTypeId'] = self.data_type_id.to_dict()
        # set to None if key (nullable) is None
        # and __fields_set__ contains the field
        if self.key is None and "key" in self.__fields_set__:
            _dict['key'] = None

        # set to None if display_name (nullable) is None
        # and __fields_set__ contains the field
        if self.display_name is None and "display_name" in self.__fields_set__:
            _dict['displayName'] = None

        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict['description'] = None

        # set to None if value_type (nullable) is None
        # and __fields_set__ contains the field
        if self.value_type is None and "value_type" in self.__fields_set__:
            _dict['valueType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QualifierDefinition:
        """Create an instance of QualifierDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QualifierDefinition.parse_obj(obj)

        _obj = QualifierDefinition.parse_obj({
            "key": obj.get("key"),
            "display_name": obj.get("displayName"),
            "description": obj.get("description"),
            "data_type_id": ResourceId.from_dict(obj.get("dataTypeId")) if obj.get("dataTypeId") is not None else None,
            "value_type": obj.get("valueType"),
            "is_required": obj.get("isRequired")
        })
        return _obj

QualifierDefinition.update_forward_refs()
