# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid.models.rec_dates_reconciled import RecDatesReconciled
from lusid.models.rec_execution import RecExecution
from lusid.models.rec_result_counts import RecResultCounts
from lusid.models.rec_review import RecReview

class RecRunLogEntry(BaseModel):
    """
    A summary of a single run of a single rec type within an instance's run log, carrying the per-run outcome  detail the grouped-by-instance overview renders. Every entry comes off a result set, so only a run that has  completed or failed appears: a run still in flight is not logged until it lands.  # noqa: E501
    """
    run_number: StrictInt = Field(description="The run number within the instance. Increments with each re-run.", alias="runNumber")
    run_as_at: datetime = Field(description="The asAt datetime at which the run happened.", alias="runAsAt")
    superseded_as_at: Optional[datetime] = Field(default=None, description="The asAt datetime at which this run was superseded by a subsequent run.", alias="supersededAsAt")
    dates_reconciled: RecDatesReconciled = Field(alias="datesReconciled")
    execution: RecExecution
    approval_status:  StrictStr = Field(...,alias="approvalStatus", description="The position of this result set in the approval ceremony. Available values: UnderReview, PendingApproval, RevisionsRequested, Approved, NotApplicable.") 
    result_counts: Optional[RecResultCounts] = Field(default=None, alias="resultCounts")
    review: Optional[RecReview] = None
    rec_result_set_href:  StrictStr = Field(...,alias="recResultSetHref", description="The specific Uniform Resource Identifier (URI) of the full rec result set this run belongs to.") 
    __properties = ["runNumber", "runAsAt", "supersededAsAt", "datesReconciled", "execution", "approvalStatus", "resultCounts", "review", "recResultSetHref"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RecRunLogEntry:
        """Create an instance of RecRunLogEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of dates_reconciled
        if self.dates_reconciled:
            _dict['datesReconciled'] = self.dates_reconciled.to_dict()
        # override the default output from pydantic by calling `to_dict()` of execution
        if self.execution:
            _dict['execution'] = self.execution.to_dict()
        # override the default output from pydantic by calling `to_dict()` of result_counts
        if self.result_counts:
            _dict['resultCounts'] = self.result_counts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of review
        if self.review:
            _dict['review'] = self.review.to_dict()
        # set to None if superseded_as_at (nullable) is None
        # and __fields_set__ contains the field
        if self.superseded_as_at is None and "superseded_as_at" in self.__fields_set__:
            _dict['supersededAsAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RecRunLogEntry:
        """Create an instance of RecRunLogEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RecRunLogEntry.parse_obj(obj)

        _obj = RecRunLogEntry.parse_obj({
            "run_number": obj.get("runNumber"),
            "run_as_at": obj.get("runAsAt"),
            "superseded_as_at": obj.get("supersededAsAt"),
            "dates_reconciled": RecDatesReconciled.from_dict(obj.get("datesReconciled")) if obj.get("datesReconciled") is not None else None,
            "execution": RecExecution.from_dict(obj.get("execution")) if obj.get("execution") is not None else None,
            "approval_status": obj.get("approvalStatus"),
            "result_counts": RecResultCounts.from_dict(obj.get("resultCounts")) if obj.get("resultCounts") is not None else None,
            "review": RecReview.from_dict(obj.get("review")) if obj.get("review") is not None else None,
            "rec_result_set_href": obj.get("recResultSetHref")
        })
        return _obj

RecRunLogEntry.update_forward_refs()
