# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid.models.reverse_stress_rung import ReverseStressRung

class ReverseStressResponse(BaseModel):
    """
    The result of a reverse stress solve: the factor the scenario's shifts must be multiplied by to  reach the target loss, together with the whole evaluated ladder so the answer can be checked  rather than taken on trust.                The ladder is part of the answer, not diagnostics. A reverse stress is only meaningful where the  loss moves in one direction with the factor, and the ladder is what shows that it does.  # noqa: E501
    """
    scale: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The solved factor: the multiple of the scenario's shifts that reaches the target. Null when no  factor within the evaluated range reaches it, in which case Converged is false and the  warnings say so.")
    target_pnl: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The change in value that was asked for, echoed back.", alias="targetPnl")
    achieved_pnl: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The change in value actually produced at the solved scale, measured by a valuation at that  factor rather than interpolated. The gap to the target is the honest error of the solve.", alias="achievedPnl")
    base_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The unstressed value of the measure over the filtered holdings.", alias="baseValue")
    stressed_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The value of the measure at the solved scale.", alias="stressedValue")
    converged: Optional[StrictBool] = Field(default=None, description="Whether the achieved change is within the requested tolerance of the target. False means the  reported scale is the best reached, not an answer to rely on.")
    method:  Optional[StrictStr] = Field(None,alias="method", description="How the bracketing factor was turned into the reported one: \"Interpolation\" on a monotone  ladder, \"Bisection\" where the ladder turned back on itself and interpolating between one  bracketing pair would have hidden the others.") 
    valuations: Optional[StrictInt] = Field(default=None, description="How many valuations the solve ran, the opening ladder counting as one.")
    ladder: Optional[List[ReverseStressRung]] = Field(default=None, description="Every factor evaluated, in increasing order, including the confirming valuations.")
    warnings: Optional[List[StrictStr]] = Field(default=None, description="Anything the caller has to know to read the scale correctly: a non-monotone ladder, a target  out of reach, a solve stopped at the iteration limit.")
    __properties = ["scale", "targetPnl", "achievedPnl", "baseValue", "stressedValue", "converged", "method", "valuations", "ladder", "warnings"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ReverseStressResponse:
        """Create an instance of ReverseStressResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in ladder (list)
        _items = []
        if self.ladder:
            for _item in self.ladder:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ladder'] = _items
        # set to None if scale (nullable) is None
        # and __fields_set__ contains the field
        if self.scale is None and "scale" in self.__fields_set__:
            _dict['scale'] = None

        # set to None if achieved_pnl (nullable) is None
        # and __fields_set__ contains the field
        if self.achieved_pnl is None and "achieved_pnl" in self.__fields_set__:
            _dict['achievedPnl'] = None

        # set to None if stressed_value (nullable) is None
        # and __fields_set__ contains the field
        if self.stressed_value is None and "stressed_value" in self.__fields_set__:
            _dict['stressedValue'] = None

        # set to None if method (nullable) is None
        # and __fields_set__ contains the field
        if self.method is None and "method" in self.__fields_set__:
            _dict['method'] = None

        # set to None if ladder (nullable) is None
        # and __fields_set__ contains the field
        if self.ladder is None and "ladder" in self.__fields_set__:
            _dict['ladder'] = None

        # set to None if warnings (nullable) is None
        # and __fields_set__ contains the field
        if self.warnings is None and "warnings" in self.__fields_set__:
            _dict['warnings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ReverseStressResponse:
        """Create an instance of ReverseStressResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ReverseStressResponse.parse_obj(obj)

        _obj = ReverseStressResponse.parse_obj({
            "scale": obj.get("scale"),
            "target_pnl": obj.get("targetPnl"),
            "achieved_pnl": obj.get("achievedPnl"),
            "base_value": obj.get("baseValue"),
            "stressed_value": obj.get("stressedValue"),
            "converged": obj.get("converged"),
            "method": obj.get("method"),
            "valuations": obj.get("valuations"),
            "ladder": [ReverseStressRung.from_dict(_item) for _item in obj.get("ladder")] if obj.get("ladder") is not None else None,
            "warnings": obj.get("warnings")
        })
        return _obj

ReverseStressResponse.update_forward_refs()
