# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Dict, Optional, Any, Union, TYPE_CHECKING
from typing_extensions import Annotated
from pydantic.v1 import BaseModel, StrictStr, StrictInt, StrictBool, StrictFloat, StrictBytes, Field, validator, ValidationError, conlist, constr
from datetime import datetime
from lusid.models.override_entry_response import OverrideEntryResponse
from lusid.models.resource_id import ResourceId
from lusid.models.suppression_entry_response import SuppressionEntryResponse
from lusid.models.version import Version

class VirtualTransactionOverrideRecord(BaseModel):
    """
    The overrides and suppressions stored against a single instrument event in a single portfolio, together  with their statuses as resolved against the requested portfolio's currently generated virtual  transactions.  # noqa: E501
    """
    instrument_event_id:  Optional[StrictStr] = Field(None,alias="instrumentEventId", description="The identifier of the instrument event this record is stored against.") 
    source_portfolio_id: Optional[ResourceId] = Field(default=None, alias="sourcePortfolioId")
    overrides: Optional[Dict[str, OverrideEntryResponse]] = Field(default=None, description="The overrides stored in this record, keyed by the virtual transaction id being overridden as it appears in the portfolio holding the record.")
    suppressions: Optional[Dict[str, SuppressionEntryResponse]] = Field(default=None, description="The suppressions stored in this record, keyed by the virtual transaction id being suppressed as it appears in the portfolio holding the record.")
    override_match_status:  Optional[StrictStr] = Field(None,alias="overrideMatchStatus", description="Whether every override and suppression entry in this record still matches a virtual transaction the event currently generates. Available values: Matched, Orphaned.") 
    override_application_status:  Optional[StrictStr] = Field(None,alias="overrideApplicationStatus", description="Whether all, some, or none of this record's override and suppression entries are currently applied. Available values: Full, Partial, Orphaned.") 
    cancel_active: Optional[StrictBool] = Field(default=None, description="True when an active event-level Cancel instruction also exists for this instrument event, taking precedence over the entries in this record.", alias="cancelActive")
    version: Optional[Version] = None
    __properties = ["instrumentEventId", "sourcePortfolioId", "overrides", "suppressions", "overrideMatchStatus", "overrideApplicationStatus", "cancelActive", "version"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self.dict(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VirtualTransactionOverrideRecord:
        """Create an instance of VirtualTransactionOverrideRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of source_portfolio_id
        if self.source_portfolio_id:
            _dict['sourcePortfolioId'] = self.source_portfolio_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in overrides (dict)
        _field_dict = {}
        if self.overrides:
            for _key in self.overrides:
                if self.overrides[_key]:
                    _field_dict[_key] = self.overrides[_key].to_dict()
            _dict['overrides'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in suppressions (dict)
        _field_dict = {}
        if self.suppressions:
            for _key in self.suppressions:
                if self.suppressions[_key]:
                    _field_dict[_key] = self.suppressions[_key].to_dict()
            _dict['suppressions'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of version
        if self.version:
            _dict['version'] = self.version.to_dict()
        # set to None if instrument_event_id (nullable) is None
        # and __fields_set__ contains the field
        if self.instrument_event_id is None and "instrument_event_id" in self.__fields_set__:
            _dict['instrumentEventId'] = None

        # set to None if overrides (nullable) is None
        # and __fields_set__ contains the field
        if self.overrides is None and "overrides" in self.__fields_set__:
            _dict['overrides'] = None

        # set to None if suppressions (nullable) is None
        # and __fields_set__ contains the field
        if self.suppressions is None and "suppressions" in self.__fields_set__:
            _dict['suppressions'] = None

        # set to None if override_match_status (nullable) is None
        # and __fields_set__ contains the field
        if self.override_match_status is None and "override_match_status" in self.__fields_set__:
            _dict['overrideMatchStatus'] = None

        # set to None if override_application_status (nullable) is None
        # and __fields_set__ contains the field
        if self.override_application_status is None and "override_application_status" in self.__fields_set__:
            _dict['overrideApplicationStatus'] = None

        # set to None if cancel_active (nullable) is None
        # and __fields_set__ contains the field
        if self.cancel_active is None and "cancel_active" in self.__fields_set__:
            _dict['cancelActive'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VirtualTransactionOverrideRecord:
        """Create an instance of VirtualTransactionOverrideRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VirtualTransactionOverrideRecord.parse_obj(obj)

        _obj = VirtualTransactionOverrideRecord.parse_obj({
            "instrument_event_id": obj.get("instrumentEventId"),
            "source_portfolio_id": ResourceId.from_dict(obj.get("sourcePortfolioId")) if obj.get("sourcePortfolioId") is not None else None,
            "overrides": dict(
                (_k, OverrideEntryResponse.from_dict(_v))
                for _k, _v in obj.get("overrides").items()
            )
            if obj.get("overrides") is not None
            else None,
            "suppressions": dict(
                (_k, SuppressionEntryResponse.from_dict(_v))
                for _k, _v in obj.get("suppressions").items()
            )
            if obj.get("suppressions") is not None
            else None,
            "override_match_status": obj.get("overrideMatchStatus"),
            "override_application_status": obj.get("overrideApplicationStatus"),
            "cancel_active": obj.get("cancelActive"),
            "version": Version.from_dict(obj.get("version")) if obj.get("version") is not None else None
        })
        return _obj

VirtualTransactionOverrideRecord.update_forward_refs()
