language: python
services:
- docker
script:
- |

  if [ "$TRAVIS_BRANCH" = "master" ]; then
    fbn_token_url="MASTER_FBN_TOKEN_URL"
    fbn_username="MASTER_FBN_USERNAME"
    fbn_password="MASTER_FBN_PASSWORD"
    fbn_clientid="MASTER_FBN_CLIENT_ID"
    fbn_client_secret="MASTER_FBN_CLIENT_SECRET"
    fbn_lusid_api_url="MASTER_FBN_LUSID_API_URL"    
    fbn_app_name="MASTER_FBN_APP_NAME"
  else
    fbn_token_url="DEVELOP_FBN_TOKEN_URL"
    fbn_username="DEVELOP_FBN_USERNAME"
    fbn_password="DEVELOP_FBN_PASSWORD"
    fbn_clientid="DEVELOP_FBN_CLIENT_ID"
    fbn_client_secret="DEVELOP_FBN_CLIENT_SECRET"
    fbn_lusid_api_url="DEVELOP_FBN_LUSID_API_URL"
    fbn_app_name="DEVELOP_FBN_APP_NAME"
  fi

  cd sdk

  export FBN_TOKEN_URL=${!fbn_token_url} \
  export FBN_USERNAME=${!fbn_username} \
  export FBN_PASSWORD=${!fbn_password} \
  export FBN_CLIENT_ID=${!fbn_clientid} \
  export FBN_CLIENT_SECRET=${!fbn_client_secret} \
  export FBN_LUSID_API_URL=${!fbn_lusid_api_url} \
  export FBN_APP_NAME=${!fbn_app_name}

  # The --abort-on-container-exit flag exits tinyproxy when the tests are finished and carries over the exit code
  docker-compose up --abort-on-container-exit

notifications:
  slack:
    rooms:
      secure: "MnBdYWpr9kBTSaB/Gof6GEyknx23ReSYAQxbZiuRvnzV4tdjJBmkAgJPcisFqJkdlZKaBEm4l750el5s3di6wV8fiDPpkc6nTjYZfTg+FbUEiZIvB9Xh+gAgZdmE9TEU41Rm0rB1XjsWJfokKjv0bJz1WgevfQuavcPwdNgEdt8YuB2CebphddFBp5m/B5EjC6fZwj3bTJZ2a2eFHJZzenF2Aui2QA80IHyeBwRJAiuDo/lpK7cWp5kQHN2DVx+IQgkoU3RKmFR3DsMN8UkPDXXLWVmRTU8amQWz3utvaUAKd7Vww06WWH6M2FVjoJ+at3a7/aq8iNz2mmuamlyd/lD7hMvmjux+q5dHpBtYSVQ8KteSLvhn7LpI18nMv4ZZmCI66PpxzhsdfCnMOrlMGlKAzygadYc7hezv3oHVqOP3bkzQzIcaftmc5vimu2j1x/LLSW7WYo4wf8yi2kLbLJd3YrAldYkRqU0CiJBYtnZE8doNKBgX2vczQD3n9bBwmX4V18lT5BQocLL+fg7Jii4YSad8nokl9HAgfNi3IP21Hu8V2Sizru0LHcF2Nej7PVOxHn4epqC75Wqt8bEDXs6UofmWv+anTutJyjB2OtKmlpiwBkeMRM1Qm0PNi7g2dh7UT3yhVvbjJxPHMq/oL9V+WHEx+vL4XkXEVstLnGg="
    on_failure: always
