# coding: utf-8

"""
    LUSID API

    FINBOURNE Technology  # noqa: E501

    Contact: info@finbourne.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import re  # noqa: F401
import io
import warnings

from pydantic.v1 import validate_arguments, ValidationError
from typing import overload, Optional, Union, Awaitable

from datetime import datetime
from pydantic.v1 import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from lusid.models.market_data_field_configuration import MarketDataFieldConfiguration
from lusid.models.update_market_data_field_configuration_request import UpdateMarketDataFieldConfigurationRequest

from lusid.api_client import ApiClient
from lusid.api_response import ApiResponse
from lusid.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)
from lusid.extensions.configuration_options import ConfigurationOptions

# ensure templated type usages are imported
from pydantic.v1 import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated

class MarketDataFieldConfigurationApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @overload
    async def get_market_data_field_configuration(self, market_data_category : Annotated[StrictStr, Field(..., description="The market data category.")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to retrieve the configuration. Defaults to return the latest version if not specified.")] = None, **kwargs) -> MarketDataFieldConfiguration:  # noqa: E501
        ...

    @overload
    def get_market_data_field_configuration(self, market_data_category : Annotated[StrictStr, Field(..., description="The market data category.")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to retrieve the configuration. Defaults to return the latest version if not specified.")] = None, async_req: Optional[bool]=True, **kwargs) -> MarketDataFieldConfiguration:  # noqa: E501
        ...

    @validate_arguments
    def get_market_data_field_configuration(self, market_data_category : Annotated[StrictStr, Field(..., description="The market data category.")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to retrieve the configuration. Defaults to return the latest version if not specified.")] = None, async_req: Optional[bool]=None, **kwargs) -> Union[MarketDataFieldConfiguration, Awaitable[MarketDataFieldConfiguration]]:  # noqa: E501
        """[EARLY ACCESS] GetMarketDataFieldConfiguration: Get a Market Data Field Configuration  # noqa: E501

        Retrieve the market data field configuration for a given market data category.  If the configuration does not yet exist, an empty configuration will be returned.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_market_data_field_configuration(market_data_category, as_at, async_req=True)
        >>> result = thread.get()

        :param market_data_category: The market data category. (required)
        :type market_data_category: str
        :param as_at: The asAt datetime at which to retrieve the configuration. Defaults to return the latest version if not specified.
        :type as_at: datetime
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: MarketDataFieldConfiguration
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_market_data_field_configuration_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.get_market_data_field_configuration_with_http_info(market_data_category, as_at, **kwargs)  # noqa: E501

    @validate_arguments
    def get_market_data_field_configuration_with_http_info(self, market_data_category : Annotated[StrictStr, Field(..., description="The market data category.")], as_at : Annotated[Optional[datetime], Field(description="The asAt datetime at which to retrieve the configuration. Defaults to return the latest version if not specified.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """[EARLY ACCESS] GetMarketDataFieldConfiguration: Get a Market Data Field Configuration  # noqa: E501

        Retrieve the market data field configuration for a given market data category.  If the configuration does not yet exist, an empty configuration will be returned.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_market_data_field_configuration_with_http_info(market_data_category, as_at, async_req=True)
        >>> result = thread.get()

        :param market_data_category: The market data category. (required)
        :type market_data_category: str
        :param as_at: The asAt datetime at which to retrieve the configuration. Defaults to return the latest version if not specified.
        :type as_at: datetime
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(MarketDataFieldConfiguration, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'market_data_category',
            'as_at'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_market_data_field_configuration" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['market_data_category']:
            _path_params['marketDataCategory'] = _params['market_data_category']


        # process the query parameters
        _query_params = []
        if _params.get('as_at') is not None:  # noqa: E501
            if isinstance(_params['as_at'], datetime):
                _query_params.append(('asAt', _params['as_at'].strftime(self.api_client.configuration.datetime_format)))
            else:
                _query_params.append(('asAt', _params['as_at']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "MarketDataFieldConfiguration",
            '400': "LusidValidationProblemDetails",
        }

        return self.api_client.call_api(
            '/api/marketdata/fieldconfiguration/{marketDataCategory}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))


    @overload
    async def update_market_data_field_configuration(self, market_data_category : Annotated[StrictStr, Field(..., description="The market data category.")], update_market_data_field_configuration_request : Annotated[UpdateMarketDataFieldConfigurationRequest, Field(description="The metadata fields to add, update, or remove.")], **kwargs) -> MarketDataFieldConfiguration:  # noqa: E501
        ...

    @overload
    def update_market_data_field_configuration(self, market_data_category : Annotated[StrictStr, Field(..., description="The market data category.")], update_market_data_field_configuration_request : Annotated[UpdateMarketDataFieldConfigurationRequest, Field(description="The metadata fields to add, update, or remove.")], async_req: Optional[bool]=True, **kwargs) -> MarketDataFieldConfiguration:  # noqa: E501
        ...

    @validate_arguments
    def update_market_data_field_configuration(self, market_data_category : Annotated[StrictStr, Field(..., description="The market data category.")], update_market_data_field_configuration_request : Annotated[UpdateMarketDataFieldConfigurationRequest, Field(description="The metadata fields to add, update, or remove.")], async_req: Optional[bool]=None, **kwargs) -> Union[MarketDataFieldConfiguration, Awaitable[MarketDataFieldConfiguration]]:  # noqa: E501
        """[EARLY ACCESS] UpdateMarketDataFieldConfiguration: Update a Market Data Field Configuration  # noqa: E501

        Update the metadata field schema for a market data field configuration.  Allows adding, updating, and removing metadata field definitions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_market_data_field_configuration(market_data_category, update_market_data_field_configuration_request, async_req=True)
        >>> result = thread.get()

        :param market_data_category: The market data category. (required)
        :type market_data_category: str
        :param update_market_data_field_configuration_request: The metadata fields to add, update, or remove. (required)
        :type update_market_data_field_configuration_request: UpdateMarketDataFieldConfigurationRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: MarketDataFieldConfiguration
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_market_data_field_configuration_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        if async_req is not None:
            kwargs['async_req'] = async_req
        return self.update_market_data_field_configuration_with_http_info(market_data_category, update_market_data_field_configuration_request, **kwargs)  # noqa: E501

    @validate_arguments
    def update_market_data_field_configuration_with_http_info(self, market_data_category : Annotated[StrictStr, Field(..., description="The market data category.")], update_market_data_field_configuration_request : Annotated[UpdateMarketDataFieldConfigurationRequest, Field(description="The metadata fields to add, update, or remove.")], **kwargs) -> ApiResponse:  # noqa: E501
        """[EARLY ACCESS] UpdateMarketDataFieldConfiguration: Update a Market Data Field Configuration  # noqa: E501

        Update the metadata field schema for a market data field configuration.  Allows adding, updating, and removing metadata field definitions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_market_data_field_configuration_with_http_info(market_data_category, update_market_data_field_configuration_request, async_req=True)
        >>> result = thread.get()

        :param market_data_category: The market data category. (required)
        :type market_data_category: str
        :param update_market_data_field_configuration_request: The metadata fields to add, update, or remove. (required)
        :type update_market_data_field_configuration_request: UpdateMarketDataFieldConfigurationRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(MarketDataFieldConfiguration, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'market_data_category',
            'update_market_data_field_configuration_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_market_data_field_configuration" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['market_data_category']:
            _path_params['marketDataCategory'] = _params['market_data_category']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['update_market_data_field_configuration_request'] is not None:
            _body_params = _params['update_market_data_field_configuration_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "MarketDataFieldConfiguration",
            '400': "LusidValidationProblemDetails",
        }

        return self.api_client.call_api(
            '/api/marketdata/fieldconfiguration/{marketDataCategory}/$update', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
